In [ ]:
"""
1. [簡答題] 請問下列四種不同的 DataFrame 選取結果有什麼差異？
df.loc[ '2013-01-01', 'A'] 
df.loc[ '2013-01-01', ['A', 'B'] ] 
df.loc[ '2013-01-01':'2013-01-02', 'A' ] 
df.loc[ '2013-01-01':'2013-01-05', 'A':'C'] 
"""

In [ ]:
"""
2. 請根據提供的資料，選擇出下列的要求：
df = pd.DataFrame(np.random.randn(6,3),columns=['col1','col2','col3'])
# - select the first 3 rows.
# - select the odd rows. (index = 1, 3, 5)
# - select the last 2 columns.
# - select the even columns. (index = 0, 2, 4)
"""

In [16]:
import numpy as np
import pandas as pd

data = pd.DataFrame(np.random.randn(6,3), columns=['col1', 'col2', 'col3'])
print('data: \n',data)

# q1 - select the first 3 rows.
q1 = data.iloc[0:4]
print('q1: \n', q1)

# q2- select the odd rows. (index = 1, 3, 5)
q2 = data.iloc[[1,3,5], :]
print('q2: \n', q2)

# q3- select the last 2 columns.
q3 = data.iloc[:, -2:]
print('q3: \n', q3)

# q4- select the even columns. (index = 0, 2)
q4 = data.iloc[:, [0,2]]
print('q4: \n', q4)

data:
        col1      col2      col3
0 -0.867294 -0.328836  0.788017
1  0.035026  0.086551  1.132949
2  0.264157 -0.400344 -0.614282
3 -2.041154 -0.428870  1.150079
4 -0.737896 -0.907447 -1.145907
5  2.076800  0.496450  0.336812
q1:
        col1      col2      col3
0 -0.867294 -0.328836  0.788017
1  0.035026  0.086551  1.132949
2  0.264157 -0.400344 -0.614282
3 -2.041154 -0.428870  1.150079
q2:
        col1      col2      col3
1  0.035026  0.086551  1.132949
3 -2.041154 -0.428870  1.150079
5  2.076800  0.496450  0.336812
q3:
        col2      col3
0 -0.328836  0.788017
1  0.086551  1.132949
2 -0.400344 -0.614282
3 -0.428870  1.150079
4 -0.907447 -1.145907
5  0.496450  0.336812
q4:
        col1      col3
0 -0.867294  0.788017
1  0.035026  1.132949
2  0.264157 -0.614282
3 -2.041154  1.150079
4 -0.737896 -1.145907
5  2.076800  0.336812

In [ ]:
"""
3. 請根據提供的資料，選擇出下列的要求：
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
# - 1. filtered by first column > 20?
# - 2. filtered by first column + second column > 50
# - 3. filtered by first column < 30 or second column > 30
# - 4. filtered by total sum of row > 100
"""

In [29]:
import numpy as np
import pandas as pd

data2 = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1,4))
print ('data2: \n', data2)

# ANS1 - 1. filtered by first column > 20?
ANS1 = data2.loc[data2[0]>20]
print('ANS1: \n', ANS1)

# ANS2 - 2. filtered by first column + second column > 50
ANS2 = data2.loc[(data2[0]+data2[1])>50]
print('ANS2: \n', ANS2)

# - 3. filtered by first column < 30 or second column > 30
ANS3 = data2.loc[(data2[0]<30) | (data2[1]>30)]
print('ANS3: \n', ANS3)

# - 4. filtered by total sum of row > 100
ANS4 = data2[(data2.sum(axis=1))>100] #axis=1 means: 橫向
print('ANS4: \n', ANS4)

data2:
      0   1   2   3
0   18  10  33  16
1   18  32  18  17
2   26  28  26  30
3   21  32  22  26
4   33  18  34  10
5   30  36  21  27
6   33  20  36  13
7   10  19  12  31
8   33  11  39  14
9   35  32  38  16
10  38  30  14  23
11  28  20  24  19
12  27  33  27  12
13  25  15  33  35
14  18  15  16  38
ANS1:
      0   1   2   3
2   26  28  26  30
3   21  32  22  26
4   33  18  34  10
5   30  36  21  27
6   33  20  36  13
8   33  11  39  14
9   35  32  38  16
10  38  30  14  23
11  28  20  24  19
12  27  33  27  12
13  25  15  33  35
ANS2:
      0   1   2   3
2   26  28  26  30
3   21  32  22  26
4   33  18  34  10
5   30  36  21  27
6   33  20  36  13
9   35  32  38  16
10  38  30  14  23
12  27  33  27  12
ANS3:
      0   1   2   3
0   18  10  33  16
1   18  32  18  17
2   26  28  26  30
3   21  32  22  26
5   30  36  21  27
7   10  19  12  31
9   35  32  38  16
11  28  20  24  19
12  27  33  27  12
13  25  15  33  35
14  18  15  16  38
ANS4:
      0   1   2   3
2   26  28  26  30
3   21  32  22  26
5   30  36  21  27
6   33  20  36  13
9   35  32  38  16
10  38  30  14  23
13  25  15  33  35